version: 2.1
orbs:
  docker: circleci/docker@0.5.19
  django-tools: pennlabs/django-tools@0.0.1
  helm-tools: pennlabs/helm-tools@0.1.1

branch-filters: &branch-filters
  filters:
    branches:
      only:
        - master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - django-tools/check:
          project-name: project_name
          project-location: backend
      - docker/publish:
          name: publish-backend
          requires:
            - django-tools/check
          path: backend
          cache_from: "pennlabs/project_name-backend:latest"
          image: "pennlabs/project_name-backend"
          tag: "${CIRCLE_SHA1},latest"
          context: docker-publish
          <<: *branch-filters
      - docker/publish:
          name: publish-frontend
          requires:
            - django-tools/check
          path: frontend
          cache_from: "pennlabs/project_name-frontend:latest"
          image: "pennlabs/project_name-frontend"
          tag: "${CIRCLE_SHA1},latest"
          context: docker-publish
          <<: *branch-filters
      - helm-tools/deploy:
          requires:
            - publish-backend
            - publish-frontend
          context: k8s-deploy
          <<: *branch-filters
