deploy_version: 0.1.8
image_tag: latest

applications:
  - name: django
    image: pennlabs/project_name-backend
    secret: project_name
    ingress:
      hosts:
        - host: api.example.com
          paths: ["/"]
    extraEnv:
      - name: BACKEND_DOMAIN
        value: api.example.com
      - name: FRONTEND_DOMAIN
        value: example.com
      - name: DJANGO_SETTINGS_MODULE
        value: project_name.settings.production
  - name: react
    image: pennlabs/project_name-frontend
    secret: project_name
    ingress:
      hosts:
        - host: example.com
          paths: ["/"]
    extraEnv:
      - name: PORT
        value: 80
